return {
	-- "folke/edgy.nvim",
	-- event = "VeryLazy",
	-- init = function()
	-- 	vim.opt.laststatus = 3
	-- 	vim.opt.splitkeep = "screen"
	-- end,
	-- opts = {
	-- 	-- enable this to exit Neovim when only edgy windows are left
	-- 	exit_when_last = true,
	-- 	-- buffer-local keymaps to be added to edgebar buffers.
	-- 	-- Existing buffer-local keymaps will never be overridden.
	-- 	-- Set to false to disable a builtin.
	-- 	---@type table<string, fun(win:Edgy.Window)|false>
	-- 	keys = {
	-- 		-- increase width
	-- 		["<c-w>>"] = function(win)
	-- 			win:resize("width", 2)
	-- 		end,
	-- 		-- decrease width
	-- 		["<c-w><lt>"] = function(win)
	-- 			win:resize("width", -2)
	-- 		end,
	-- 		-- reset all custom sizing
	-- 		["<c-w>="] = function(win)
	-- 			win.view.edgebar:equalize()
	-- 		end,
	-- 	},
	-- 	bottom = {
	-- 		"Trouble",
	-- 		{ ft = "qf",            title = "QuickFix" },
	-- 		{
	-- 			ft = "help",
	-- 			size = { height = 20 },
	-- 			-- only show help buffers
	-- 			filter = function(buf)
	-- 				return vim.bo[buf].buftype == "help"
	-- 			end,
	-- 		},
	-- 		{ ft = "spectre_panel", size = { height = 0.4 } },
	-- 	},
	-- 	left = {
	-- 		-- Neo-tree filesystem always takes half the screen height
	-- 		{
	-- 			title = "Neo-Tree",
	-- 			ft = "neo-tree",
	-- 			filter = function(buf)
	-- 				return vim.b[buf].neo_tree_source == "filesystem"
	-- 			end,
	-- 			size = { height = 0.5 },
	-- 		},
	-- 		{
	-- 			title = function()
	-- 				local buf_name = vim.api.nvim_buf_get_name(0) or "[No Name]"
	-- 				return vim.fn.fnamemodify(buf_name, ":t")
	-- 			end,
	-- 			ft = "Outline",
	-- 			pinned = true,
	-- 			open = "Outline",

	-- 		},
	-- 	},
	-- },
}
