require("plugins.cmp")
require("plugins.easypick")
require("plugins.lsp_config")
require("plugins.lsp_lines")
require("plugins.mini_bracketed")
require("plugins.telescope")
require("plugins.dap")
require("plugins.dap_ui")
